apiVersion: v1
kind: Service
metadata:
  labels:
    app: snmpexporter
  name: prober
spec:
  ports:
  - name: probe
    port: 9190
    protocol: TCP
    targetPort: 9190
  selector:
    app: snmpexporter
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: snmpexporter
  name: snmpexporter
spec:
  replicas: 5
  selector:
    matchLabels:
      app: snmpexporter
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 3
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: snmpexporter
      name: snmpexporter
    spec:
      containers:
      - image: ghcr.io/tinboxlabs/snmpexporter:quay
        imagePullPolicy: ifNotPresent
        name: snmpexporter
        volumeMounts:
          - name: config-volume
            mountPath: /etc/snmpexporter
        resources:
              requests:
                memory: "300Mi"
              limits:
                memory: "400Mi"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 9190
          initialDelaySeconds: 15
          timeoutSeconds: 30
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: snmpexporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name snmpexporter
data:
  snmpexporter.yaml: |
    snmp:
      public:
        community: public
        version: 2

    override:
      # bsnDot11EssNumberOfMobileStations is reported as a Counter
      .1.3.6.1.4.1.14179.2.1.1.1.38: INTEGER

    annotator:

      # Labelification is used to turn strings into labels on metrics that
      # otherwise do not have any numeric data. The value will be fixed to 1
      # and the string value will be moved to a label called 'value' and 'hex'.
      # Use this if you don't have any sensible OID to annotate with the value or
      # there isn't a 1:1 match between the index and the value you wish to use.
      #
      # 'value' contains the human readable characters only and is striped.
      # 'hex' is the raw data but hex encoded.
      # If the raw string value is empty the result is dropped
      labelify:
        - .1.3.6.1.2.1.47.1.1.1.1.9  # entPhysicalFirmwareRev
        - .1.3.6.1.2.1.47.1.1.1.1.11 # entPhysicalSerialNum
        - .1.3.6.1.2.1.47.1.1.1.1.13 # entPhysicalModelName
        - .1.3.6.1.4.1.9.9.380.1.1.8 # cdsRelayAgentInfoOptRemoteIdSub
        - .1.3.6.1.2.1.75.1.1.5.1.2 # fcFxPortName

      annotations:
        - annotate:
            - .1.3.6.1.2.1.2.2.1                 # ifTable
            - .1.3.6.1.2.1.31.1.1                # ifXEntry
            - .1.3.6.1.4.1.9.9.46.1.6.1.1        # vlanTrunkPortEntry
            # Note that cErrDisableIfStatusCause uses "ifIndex.0" as index, so we
            # need to use [1] to annotate against ifTable
            - .1.3.6.1.4.1.9.9.548.1.3.1.1.2[1]  # cErrDisableIfStatusCause
          with:
            interface: .1.3.6.1.2.1.2.2.1.2  # ifDescr
            alias: .1.3.6.1.2.1.31.1.1.1.18  # ifAlias

        - annotate:
            - .1.3.6.1.2.1.17.4.3.1.2     # dot1dTpFdbStatus (mac -> port)
            - .1.3.6.1.2.1.17.2.15.1.3    # dot1dStpPortState
          with:
            # These OIDs use the port so we need to map the port to ifIndex first
            # through .1.3.6.1.2.1.17.1.4.1.2
            interface: .1.3.6.1.2.1.17.1.4.1.2 > .1.3.6.1.2.1.2.2.1.2  # ifDescr
            alias: .1.3.6.1.2.1.17.1.4.1.2 > .1.3.6.1.2.1.31.1.1.1.18  # ifAlias

        - annotate:
            - .1.3.6.1.4.1.9.9.91.1.1.1.1.4    # entSensorValue
          with:
            sensor: .1.3.6.1.2.1.47.1.1.1.1.2   # entPhysicalDesc
            type: .1.3.6.1.4.1.9.9.91.1.1.1.1.1 # entSensorType
            # TODO(bluecmd): This might be better to map to a proper
            # scale so that we can do entSensorValue / entSensorScale
            # TOOD(bluecmd): We want to do OID value resolution for
            # these kind of oids. Right now we save e.g "7", while we
            # should save "millis".
            scale: .1.3.6.1.4.1.9.9.91.1.1.1.1.2 # entSensorScale

        - annotate:
            - .1.3.6.1.2.1.47.1.1.1.1.11    # entPhysicalSerialNum
          with:
            inside: .1.3.6.1.2.1.47.1.1.1.1.4 # entPhysicalContainedIn
            name: .1.3.6.1.2.1.47.1.1.1.1.2   # entPhysicalDesc

        - annotate:
            - .1.3.6.1.4.1.14179.2.1.1.1.38      # bsnDot11EssNumberOfMobileStation
          with:
            essid: .1.3.6.1.4.1.14179.2.1.1.1.2  # bsnDot11EssSsid

        - annotate:
            - .1.3.6.1.4.1.9.9.548.1.3.1.1.2      # cErrDisableIfStatusCause
          with:
            vlan: .1.3.6.1.4.1.9.9.548.1.3.1.1.1  # cErrDisableIfStatusVlanIndex

        - annotate:
            - .1.3.6.1.4.1.9.9.513.1.1.1         # cLApTable
            - .1.3.6.1.4.1.9.9.513.1.2.2         # cLApEthernetIfTable
          with:
            ap: .1.3.6.1.4.1.9.9.513.1.1.1.1.5   # cLApName

        - annotate:
            - .1.3.6.1.4.1.12356.101.13.2 # fgHaTables
          with:
            serial: .1.3.6.1.4.1.12356.101.13.2.1.1.2  # fgHaStatsSerial
            name: .1.3.6.1.4.1.12356.101.13.2.1.1.11   # fgHaStatsHostname
            master: .1.3.6.1.4.1.12356.101.13.2.1.1.16 # fgHaStatsMasterSerial

        - annotate:
            - .1.3.6.1.4.1.12356.101.4.3.2.1.3 # fgHwSensorEntValue
            - .1.3.6.1.4.1.12356.101.4.3.2.1.4 # fgHwSensorEntAlarmStatus
          with:
            name: .1.3.6.1.4.1.12356.101.4.3.2.1.2  # fgHwSensorEntName

    exporter:
      convert:
        csyClockDateAndTime: DateTime

    collection:
      Default OIDs:
        models:
          - .*
        oids:
          - .1.3.6.1.2.1.1.3            # sysUptime
          - .1.3.6.1.2.1.47.1.1.1.1.13  # entPhysicalModelName

      Cisco Nexus Switch:
        # Nexus has a lot of weird things going with it w.r.t. SNMP
        # and handles unknown OIDs quite poorly. Keep it seperate
        # to only poll known good OIDs.
        models:
          - ^N.K-
          - ^N5K
          - ^N5600
        layers:
          - public
        oids:
          # Known slow oids:
          # - .1.3.6.1.2.1.105.1.0 (pethObjects)
          # - .1.3.6.1.4.1.9.2.1.0 (lcpu)
          - .1.3.6.1.2.1.2.2               # ifTable
          - .1.3.6.1.2.1.2.2.1.14          # ifInErrors
          - .1.3.6.1.2.1.2.2.1.2           # ifDescr
          - .1.3.6.1.2.1.2.2.1.20          # ifOutErrors
          - .1.3.6.1.2.1.2.2.1.7           # ifAdminStatus
          - .1.3.6.1.2.1.2.2.1.8           # ifOperStatus
          - .1.3.6.1.2.1.31.1.1            # ifXEntry
          - .1.3.6.1.2.1.31.1.1.1.10       # ifHCOutOctets
          - .1.3.6.1.2.1.31.1.1.1.15       # ifHighSpeed
          - .1.3.6.1.2.1.31.1.1.1.18       # ifAlias
          - .1.3.6.1.2.1.31.1.1.1.6        # ifHCInOctets
          - .1.3.6.1.2.1.47.1.1.1.1.11     # entPhysicalSerialNum
          - .1.3.6.1.2.1.47.1.1.1.1.13     # entPhysicalModelName
          - .1.3.6.1.2.1.47.1.1.1.1.2      # entPhysicalDesc
          - .1.3.6.1.2.1.47.1.1.1.1.9      # entPhysicalFirmwareRev
          - .1.3.6.1.4.1.9.9.109.1.1.1.1   # cisco CPU
          - .1.3.6.1.4.1.9.9.131.1.1       # csyClock
          - .1.3.6.1.4.1.9.9.380.1.1       # cdsGlobal
          - .1.3.6.1.4.1.9.9.91.1.1.1.1.1  # entSensorType
          - .1.3.6.1.4.1.9.9.91.1.1.1.1.2  # entSensorScale
          - .1.3.6.1.4.1.9.9.91.1.1.1.1.4  # entSensorValue
          - .1.3.6.1.4.1.9.9.548.1.3.1     # cErrDisableIfStatusTable

